### ISSUE TITLE
Profile: 'false' is still applying optimizations

### ISSUE THREAD

**Issue by urbgimtam** [harlan-zw/nuxt-build-optimisations#21]
**Describe the bug**
When module is installed and buildOptimisations profile is 'false', I still get 2x to 3x faster build times.
When module is uninstalled, build times go back to regular.

**To Reproduce**
1. Install module and configure buildOptimisations.profile as 'false'
2. Run nuxt build and store the measures for client and server
3. Uninstall module (and remove settings from nuxt.config.js).
4. Run nuxt build and store the measures for client and server

**Expected behavior**
When module is installed and buildOptimisations profile is 'false', it should not perform any optimization.

**Comment by urbgimtam** [comment]
Maybe linked to #20 'Avoid overriding users default nuxt configurations' ?

**Comment by harlan-zw** [comment]
Hey @urbgimtam 

Apologies for the many months of delay... I did fix this in 1.0.3 I believe but the logger was still showing it was disabled, that should be fixed now.
