### ISSUE TITLE
Fails with vue-property-decorator and vue-class-component

### ISSUE THREAD

**Issue by husayt** [harlan-zw/nuxt-build-optimisations#24]
**Describe the bug**
I'm getting this errors in experimental mode:
```
Module build failed (from ./node_modules/esbuild-loader/dist/index.js):                       friendly-errors 11:22:51
Error: Transform failed with 1 error:
...\components\page\View.vue:29:0: error: Unexpected "@"
```

**To Reproduce**
I guess this is to do with use of Decorators in `vue-property-decorator` and [vue-class-component](https://github.com/vuejs/vue-class-component). I have  `"experimentalDecorators": true,`

**Comment by husayt** [comment]
update: this is related to esbuild-loader. When I switch it off, this works fine. Probably can be closed here, as issue is with other library. But maybe, there is a workaround

**Comment by harlan-zw** [comment]
Hey @husayt 

Sorry for taking so many months to get back to you... I took a look, it seems that if you switch to using typescript within your components then you can make use of these features within esbuild, at least the class component ones.

Have updated the read me for this gotcha https://github.com/harlan-zw/nuxt-build-optimisations#vue-property-decorator--vue-class-component
