### ISSUE TITLE
can't find This dependency  `.nuxt/client.js `

### ISSUE THREAD

**Issue by icai** [harlan-zw/nuxt-build-optimisations#26]
**Describe the bug**

 ERROR  Failed to compile with 1 errors                                                                                                                                          friendly-errors 23:29:38

This dependency was not found:                                                                                                                                                   friendly-errors 23:29:38
                                                                                                                                                                                 friendly-errors 23:29:38
* /Users/terry/neoncms/.nuxt/client.js in multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
                                                                                                                                                                                 friendly-errors 23:29:38
To install it, you can run: npm install --save /Users/terry/neoncms/.nuxt/client.js                                                                                              friendly-errors 23:29:38

✖ Client
  Compiled with some errors in 706.15ms

✖ Server
  Compiled with some errors in 333.29ms

**To Reproduce**
package:

```
"nuxt": "^2.15.3",
"nuxt-i18n": "^6.22.1",
"nuxt-seo": "^1.5.0",
"@nuxtjs/auth": "^4.9.1",
"@nuxtjs/axios": "^5.13.1",
"@w3cub/nuxt-express-module": "^0.0.24",
 "nuxt-build-optimisations": "^1.0.2",
 "nuxt-svg-loader": "^1.2.0",
```

config

```
export default {
  // mode: 'universal',
  srcDir: 'client/',

  server: {
    // port: 3100, // default: 3000
    host: '0.0.0.0' // default: localhost
  },
  alias: {
    'assets': resolve(__dirname, './client/assets'),
    '~themes': resolve(__dirname, './client/themes')
  },
 buildModules: [
    'nuxt-build-optimisations',
    // 'nuxt-vite',
    // '~modules/svg.js',
    ['@nuxtjs/eslint-module', { fix: true }]
  ],
  buildOptimisations: {
    // profile: process.env.NODE_ENV === 'development' ? 'risky' : 'experimental'
    profile: false
  },

  /*
  ** Nuxt.js modules
  */
  modules: [
    ['nuxt-i18n'],
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/auth',
    ['@w3cub/nuxt-express-module', { expressPath: '../server/', setupPath: '../server/app.js' }], //, routesPath: 'server/routes',
    // "@nuxtjs/svg"
    // '@nuxtjs/pwa',

  ],
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1061012/112499169-30648d00-8dc2-11eb-8a11-2d0dd5adfdd3.png)

**Comment by harlan-zw** [comment]
Hey @icai 

Thanks for the issue and sorry about the delay

I've tried to replicate this but had some issues. Are you able to provide a reproduction repo?

I will warn you though, there may be a conflict with `@w3cub/nuxt-express-module` which is deprecated, have you considered moving away from it?

**Comment by harlan-zw** [comment]
Going to close this for now, please re-open if you have a reproduction repo
