### ISSUE TITLE
can't use measure option

### ISSUE THREAD

**Issue by hingjip** [harlan-zw/nuxt-build-optimisations#28]
**Describe the bug**
When I set the measure option to true. It will throw "nuxt.hook is not a function" error.
nuxt version: 2.14.4
nuxt-build-optimisations version: 1.5.0

**To Reproduce**
1. install nuxt-build-optimisations
2. set buildModules: ['nuxt-build-optimisations']
3. set buildOptimisations: { profile: 'safe', measure: true }

**Expected behavior**
Show SMP result and build successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/32975322/124630050-9ded8280-deb4-11eb-895e-0b8c8d673e1a.png)

**Additional context**
If I remove measure option, it works fine.

**Comment by harlan-zw** [comment]
Hey @hingjip 

Thanks for the issue, apologies for the long delay. I missed the notification.

Will be fixed in 1.0.6
